-- ⚠️  DEPRECATED — DO NOT USE
-- ============================================================
-- This file is from the original Supabase SDK version of the project.
-- The project has since been migrated to Prisma ORM.
--
-- The single source of truth for the database schema is:
--   prisma/schema.prisma
--
-- To set up or update the database, run:
--   npx prisma db push
--   npx prisma generate
--
-- To seed initial data:
--   npm run db:seed
--
-- This file is kept for historical reference only.
-- ============================================================
