// /home/z/my-project/src/lib/auth.ts
// Cookie-based session authentication for the admin dashboard.
//
// Reform (Bot-First):
//   - Password login has been REMOVED. The only entry point is a Magic Link
//     generated by the Telegram/WhatsApp bot via /api/auth/generate-magic-link.
//   - The session cookie is set by /api/auth/verify after a successful token consumption.
//   - All other behaviour (cookie shape, getCurrentUser, RBAC) is unchanged.

import { cookies } from 'next/headers'
import crypto from 'crypto'
import { db } from './db'

export const SESSION_COOKIE = 'drb_session'
const SESSION_MAX_AGE = 60 * 60 * 24 * 7 // 7 days

// HMAC key derived from BOT_API_SECRET for session token signing
function getSessionSecret(): string {
  return process.env.BOT_API_SECRET || 'dev-session-secret-change-me'
}

function hmacToken(token: string): string {
  return crypto.createHmac('sha256', getSessionSecret()).update(token).digest('hex')
}

export const MAX_FAILED_ATTEMPTS = 5
export const LOCKOUT_MINUTES = 15

// ---------- Session creation (called ONLY by /api/auth/verify) ----------

export async function createSessionForUser(
  userId: string,
  meta?: { ipAddress?: string; userAgent?: string }
) {
  const user = await db.adminUser.findUnique({
    where: { id: userId },
    include: { doctor: true },
  })
  if (!user || !user.isActive) return null

  await db.adminUser.update({
    where: { id: user.id },
    data: { lastLoginAt: new Date() },
  })

  await db.auditLog.create({
    data: {
      adminUserId: user.id,
      action: 'magic_link_login',
      detail: 'Authenticated via bot-issued magic link',
      ipAddress: meta?.ipAddress,
    },
  })

  const token = crypto.randomBytes(32).toString('hex')
  const tokenHash = hmacToken(token)

  // Store the session token hash in passwordHash (field is unused since password auth was removed)
  await db.adminUser.update({
    where: { id: user.id },
    data: { passwordHash: tokenHash },
  })

  const cookieStore = await cookies()
  cookieStore.set(SESSION_COOKIE, `${user.id}:${token}`, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: SESSION_MAX_AGE,
    path: '/',
  })

  return user
}

// ---------- Session reading (used by all protected API routes) ----------

export async function getCurrentUser() {
  const cookieStore = await cookies()
  const raw = cookieStore.get(SESSION_COOKIE)?.value
  if (!raw) return null

  const separatorIdx = raw.indexOf(':')
  if (separatorIdx === -1) return null

  const userId = raw.substring(0, separatorIdx)
  const token = raw.substring(separatorIdx + 1)
  if (!userId || !token) return null

  const user = await db.adminUser.findUnique({
    where: { id: userId },
    include: { doctor: true },
  })

  if (!user || !user.isActive) return null

  // Verify the session token matches the stored hash
  if (!user.passwordHash) return null
  const expectedHash = hmacToken(token)
  if (!crypto.timingSafeEqual(Buffer.from(user.passwordHash), Buffer.from(expectedHash))) {
    return null
  }

  return user
}

export async function logout() {
  const cookieStore = await cookies()
  cookieStore.delete(SESSION_COOKIE)
}

export async function getFailedAttempts(email: string): Promise<number> {
  const since = new Date(Date.now() - LOCKOUT_MINUTES * 60 * 1000)
  return db.failedLogin.count({
    where: { email, attemptedAt: { gte: since } },
  })
}

export async function recordFailedLogin(email: string, ipAddress?: string, adminUserId?: string) {
  await db.failedLogin.create({
    data: { email, ipAddress, adminUserId },
  })
}

export async function clearFailedLogins(email: string) {
  await db.failedLogin.deleteMany({ where: { email } })
}

export function getIpAddress(req: Request): string | undefined {
  const forwarded = req.headers.get('x-forwarded-for')
  if (forwarded) return forwarded.split(',')[0].trim()
  const real = req.headers.get('x-real-ip')
  if (real) return real
  return undefined
}

export function getUserAgent(req: Request): string | undefined {
  return req.headers.get('user-agent') || undefined
}
